### ISSUE TITLE
Improve theme code

### ISSUE THREAD

**Issue by K4rakara** [GoldElysium/hefs-website#128]
[This](https://github.com/GoldElysium/hefs-website/blob/d85f1707bed5c5520810adad68ebfeccb20af6ac/pages/projects/%5Bid%5D.tsx#L147-L150) isn't very scalable-- perhaps a better design would be to create a function `setTheme` and have it called once the data has been fetched, defaulting to the normal theme,  transitioning into the new one with a css transition.

**Comment by GoldElysium** [comment]
This is already planned to be addressed by #119, theme will be passsed as a prop and can be used that way. That solution was a temporary one.
