### ISSUE TITLE
Using markdown code blocks results in white text on white background

### ISSUE THREAD

**Issue by Ninjastahr** [GoldElysium/hefs-website#72]
![image](https://user-images.githubusercontent.com/10507354/118817529-ef946c00-b878-11eb-964b-e2d78b803ffb.png)

Minor styling issue; if you use Markdown code blocks, the background and text are both white, rendering it impossible to read.
(This is on the project page)

```
Markdown code block
```

**Comment by GoldElysium** [comment]
More info:
This should be properly styled by `react-markdown` and the css we're using for markdown, but it isn't.

**Comment by GoldElysium** [comment]
![image](https://user-images.githubusercontent.com/48455312/119258969-4200c000-bbcc-11eb-8f65-bb1381951265.png)
Codeblocks work fine here?

**Comment by GoldElysium** [comment]
Resolved in #95
